### ISSUE TITLE
"My Courses" page flashes before refreshing to the login page

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#1]
1) Open http://dev.westudee.com
2) "My Courses" page flashes/shows
3) Redirects? to http://dev.westudee.com/?#/login

**Comment by derrick773** [comment]
Using Google Chrome v40.0.2214.115 m on Windows 7 on my laptop

**Comment by yutarochan** [comment]
Fixed - Issue with user redirection.
