### ISSUE TITLE
Internet Explorer rendering

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#10]
Internet Explorer 11 for Windows 7 on my laptop.

Not sure why the logo is rendering in the middle of the page. See screenshot.

![image](https://cloud.githubusercontent.com/assets/11150146/6320212/5a7ae940-baa6-11e4-999b-d28292180c6d.png)

**Comment by yutarochan** [comment]
Fixed - Logo height rendering adjusted
