### ISSUE TITLE
Internet explorer rendering

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#11]
Internet Explorer 11 for Windows 7 on my laptop

Blank space to the right in IE11. See screenshot.

![image](https://cloud.githubusercontent.com/assets/11150146/6320230/aa80560a-baa6-11e4-8ac7-97dc747f2662.png)

**Comment by yutarochan** [comment]
Duplicate of: https://github.com/WeStudee/WeStudee/issues/10

**Comment by yutarochan** [comment]
Resolved - Fixed logo height rendering.
