### ISSUE TITLE
"Profile" page - extra space in BLUE seems unnecessary from a UX perspective and requires the user to scroll down

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#13]
![image](https://cloud.githubusercontent.com/assets/11150146/6320340/5a0f0480-baa8-11e4-9c0a-e6c2ccac1cac.png)

**Comment by derrick773** [comment]
Reduce the height of the blue section if possible

**Comment by derrick773** [comment]
Using Google Chrome v40.0.2214.115 m on Windows 7 on my laptop

**Comment by yutarochan** [comment]
Resolved - Extra padding off of blue background has been reduced.
