### ISSUE TITLE
Password reset issue

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#14]
1) 
![image](https://cloud.githubusercontent.com/assets/11150146/6320353/bce6e10e-baa8-11e4-9dee-d6534a97675f.png)

2) 
![image](https://cloud.githubusercontent.com/assets/11150146/6320356/c624f864-baa8-11e4-95b5-46a65e3776b6.png)

3) 
![image](https://cloud.githubusercontent.com/assets/11150146/6320358/ccf816c6-baa8-11e4-93c2-48c82532e225.png)

Link clicked:
https://www.parse.com/apps/westudee/request_password_reset?token=Qn8sOtH2yS2Brz80WMuxWJ4KM&username=derrick773%40gmail.com

**Comment by derrick773** [comment]
Using Google Chrome v40.0.2214.115 m on Windows 7 on my laptop

**Comment by yutarochan** [comment]
Similar to https://github.com/WeStudee/WeStudee/issues/3
Configuration error on Parse Application

**Comment by yutarochan** [comment]
Issue Resolved - Password reset functionality should work as per wireframe docs.
