### ISSUE TITLE
Password Reset Issue

### ISSUE THREAD

**Issue by yejipark** [WeStudee/WeStudee#17]
Using Google Chrome on my laptop (Windows 8).

1) 
![0](https://cloud.githubusercontent.com/assets/11168182/6424192/cd27ed84-bec1-11e4-8c18-922447ed5416.jpg)

2)
![1](https://cloud.githubusercontent.com/assets/11168182/6424190/cd27875e-bec1-11e4-9125-03310f61050e.jpg)

3) If I follow the link, the login page (not password reset page) comes out. I tried typing a wrong password, but then it says "Email or Password is incorrect."
![2](https://cloud.githubusercontent.com/assets/11168182/6424191/cd27a734-bec1-11e4-880a-3e395acd64d4.jpg)

**Comment by yutarochan** [comment]
Resolved - Link should lead you to a password reset page.
Typing a wrong password will give you the error "Email or Password is incorrect."
