### ISSUE TITLE
Clicking "WeStudee" logo does not navigate back to the homepage

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#2]
http://dev.westudee.com/?#/login

**Comment by derrick773** [comment]
Using Google Chrome v40.0.2214.115 m on Windows 7 on my laptop

**Comment by derrick773** [comment]
![image](https://cloud.githubusercontent.com/assets/11150146/6320295/8699897c-baa7-11e4-882c-e46ad8557639.png)

**Comment by yutarochan** [comment]
Issue has been resolved - clicking should now take you to the homepage of WeStudee.
Should this functionality be available on all places within the login, signup and password reset as well?

**Comment by derrick773** [comment]
Yes
