### ISSUE TITLE
Internet Explorer - WeStudee site does not open

### ISSUE THREAD

**Issue by yejipark** [WeStudee/WeStudee#20]
![7](https://cloud.githubusercontent.com/assets/11168182/6424347/49e6a98e-bec5-11e4-8b73-e4fe1a8097a4.jpg)

Using IE on my laptop (Windows 8). dev.westudee.com site does not get open.

**Comment by yutarochan** [comment]
Resolved - Should work again. (Perhaps you were using the site while I was performing maintenance on the server, so it did not render anything during that period).
