### ISSUE TITLE
Mobile - cannot look profile, log out, etc

### ISSUE THREAD

**Issue by yejipark** [WeStudee/WeStudee#21]
![11026367_803521509727436_2099884163_n](https://cloud.githubusercontent.com/assets/11168182/6424386/4573b2d8-bec6-11e4-9783-ee20002fbee2.jpg)

Using Chrome on my mobile phone (Samsung Android). 
I can access the site and log in, but cannot view or edit my profile (the three white lines in the left up corner is supposed to lead me into Profile/Logout etc, but if I click that, nothing happens).

**Comment by yutarochan** [comment]
Mobile is currently not supported - will address issue once web application is fully functional.
