### ISSUE TITLE
Email verification does not work

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#3]
Getting the following error after clicking the "activation link" in the email received from no-reply@parseapps.com:

https://www.parse.com/apps/westudee/verify_email?token=uIbO1ysCHW2nxyq2c2MSUPRsy&username=derrick773%40gmail.com

File not found (404 error)
If you think what you're looking for should be here, please contact the site owner.

URL loaded:
http://www.westudee.com/ws/app/?#/activated?username=derrick773%40gmail.com

**Comment by derrick773** [comment]
Using Google Chrome v40.0.2214.115 m on Windows 7 on my laptop

**Comment by derrick773** [comment]
![image](https://cloud.githubusercontent.com/assets/11150146/6320289/706519dc-baa7-11e4-802a-50d231fc5046.png)

**Comment by yutarochan** [comment]
[Additional Functionality Specifications]
Resend email verification upon logging in and checking to see if user did not verify their email.

**Comment by yutarochan** [comment]
Closed - Additional resend functionality appended.
