### ISSUE TITLE
Students Not Listed in Courses

### ISSUE THREAD

**Issue by jwhipple26** [WeStudee/WeStudee#31]
Ashwin and I are testing the ability to request a study session and have lost the ability to see fellow students in the same class.

![screenshot 2015-03-14 12 16 03](https://cloud.githubusercontent.com/assets/10063859/6652410/f571eece-ca43-11e4-9f1f-79c0ffe655b9.png)

Not sure if something was adjusted since yesterday (3/13) when I registered for Public Speaking in order to send Ashwin a request (which he did receive).

**Comment by yutarochan** [comment]
Did Ashwin also enroll in the course as well?

**Comment by jwhipple26** [comment]
Yes, we coordinated classes in order to test the notification/request process.  He also does not see me in the class (I created two IDs to test myself as well, so there should be at least 3 students in the Public Speaking class).
