### ISSUE TITLE
First time logging into WeStudee

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#4]
Logged into my account (derrick773@gmail.com) and brought to a blank "My Courses" page. Functional specifications call for the completion of the user's profile information upon first login.

**Comment by derrick773** [comment]
Using Google Chrome v40.0.2214.115 m on Windows 7 on my laptop

**Comment by yutarochan** [comment]
- Force user to provide info prior to using application (1st time).
- Show profile from 2nd time (maybe use a subtle notice to remind).

Note: See wireframe spec sheet for min content (see starred section).

**Comment by yutarochan** [comment]
Closed - Functionality added as per description above.
