### ISSUE TITLE
"Profile" edit - cannot edit the about section

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#5]

**Comment by derrick773** [comment]
Using Google Chrome v40.0.2214.115 m on Windows 7 on my laptop

**Comment by derrick773** [comment]
![image](https://cloud.githubusercontent.com/assets/11150146/6320319/e6e4efd8-baa7-11e4-8acf-aa8b0b23ff4f.png)

**Comment by yutarochan** [comment]
Solved - Edit button fixed to redirect to profile edit page.
