### ISSUE TITLE
Mouse Over Incorrect on Send Request

### ISSUE THREAD

**Issue by jwhipple26** [WeStudee/WeStudee#58]
A little difficult to grab via screenshot, but the curser arrow changes to a "text curser" while over the SEND REQUEST button.  The curser changes to the "hand curser" while over the VIEW PROFILE button.

The error occurs in the list of available students under the courses.

![screenshot 2015-04-11 14 06 12](https://cloud.githubusercontent.com/assets/10063859/7102644/73b9684a-e054-11e4-8f1f-83754f2f8297.png)

**Comment by yutarochan** [comment]
Patched: Fixed so that upon hover, the cursor turns into :point_up_2:
