### ISSUE TITLE
Preferred Email and Email ID

### ISSUE THREAD

**Issue by jwhipple26** [WeStudee/WeStudee#61]
I registered an account under email X, then updated the preferred email address to email Y.  I logged out of WeStudee.

When I went to log back into my account, then email Y (my preferred email address) received an error message.  Email X (initial registered email address) did work successfully.

Is this the intent?  If so, then should we annotate the preferred email address to indicate that the initial email is still required to sign in?  I think this will lead to some confusion.

**Comment by yutarochan** [comment]
The preferred email is not the email used to log in. As per spec, its the email that is used for via communication outside of the application. (Unless I have this misinterpreted...)

I think to clarify this, we should include some type of annotation noting the email is not used for logging in, but specifically for communication.

**Comment by derrick773** [comment]
The initial email is required to sign in. I agree that we should annotate the preferred address so that users are not confused (i.e. "This is not your login email address")

**Comment by jwhipple26** [comment]
I imagine the annotation is the best workaround for MVP, but think the better UX is to have one email address.

I always thought the .edu email was required as a filter to only allow college students.  I suspect best practice is to have one email address associated with the account.  It is probably confusing to have one email as a login and one email for communication.

I would tag syncing email addresses as a lower priority at this time.  Based on use, then we can prioritize based on student feedback.

**Comment by yutarochan** [comment]
Okay then, I'll simply add the annotation and leave the backend functionality as is for now.
