### ISSUE TITLE
Email Notification of Study Request

### ISSUE THREAD

**Issue by jwhipple26** [WeStudee/WeStudee#62]
I created multiple accounts to test notifications.  I also changed my preferred email address on one account.  

I sent a study request to myself (ID 1 to ID 2) and did not receive any email notification to the main email address or preferred email address associated with any of the accounts.

The notifications were present once logged into WeStudee.

**Comment by yutarochan** [comment]
Had some issues with the email modules and is not currently included. How should the settings for email be worked out? Should users have the option to opt-in or out of notifications when receiving requests?

**Comment by derrick773** [comment]
I don't think the opt out or in functionality is needed. All users should receive an email at their preferred email address if a notification (study request) is received.

**Comment by jwhipple26** [comment]
Agree with Derrick.

**Comment by yutarochan** [comment]
Patched: Email module is now embedded into the system. I am going to be using a third party extension to provide the functionality for its reliability and its reputation for getting emails that will "not" be sent to the spam box. The service is called SendGrid (https://sendgrid.com/home-two), and I am on a quota for 400 emails a day for the free tier. If you feel this service is necessary, please consider the pricing options and support a plan to purchase for support. (I recommend the Bronze package).

**Comment by jwhipple26** [comment]
Thanks, I think SendGrid is pretty solid.  We can look to anticipate future email needs based on traction, but for the foreseeable future, I'd be surprised if the emails per day exceeded 400.  Under the Bronze package, then we could potentially use SendGrid as the email platform for marketing emails as well.
