### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by jwhipple26** [WeStudee/WeStudee#63]
Per Goodwin's request, students should be required to upload a picture as part of the registration process.

In order to prioritize bugs prior to initial user testing on 4/15, then I think the default profile picture of the blond woman should be removed.

I think it would be fine to create the required field in advance of the 5/11 release.  It also may cause confusion and/or hinder onboarding if students are required to upload a photo during testing because not all students may have images in cloud accounts (as students will test via Goodwin computers).

@derrick773, please opine on how to handle pictures for next week.  Does this make sense?

**Comment by yutarochan** [comment]
The profile picture of the blonde woman is temporary for now.
Patched: I've removed the picture until I re-implement a feature for adding profile pictures.
