### ISSUE TITLE
Edit Availability

### ISSUE THREAD

**Issue by jwhipple26** [WeStudee/WeStudee#64]
Is there a way to edit/change availability?  I didn't see it in my review, so if the service does have the functionality, please let us know.  We may want to change UX and/or functionality to make it more prevalent.

**Comment by yutarochan** [comment]
The service does have that functionality - I just forgot to push that version up.
Going to be pushing more things throughout the day and will post updates on Slack.

**Comment by jwhipple26** [comment]
Thanks.
