### ISSUE TITLE
Add availability indicators to Dashboard matches

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#67]
Add availability indicators so that users can see other users availability. If you don't think its needed because the algorithm does that availability matching behind the scenes, then let's discuss. User A would have to talk to User B in that scenario about what day/time they are available. That is not displayed on User B's profile when User A looks at it.

![image](https://cloud.githubusercontent.com/assets/11150146/7108966/9943e978-e162-11e4-923f-3d68f96f320f.png)

**Comment by derrick773** [comment]
I do not see the user's availability on his profile:
![image](https://cloud.githubusercontent.com/assets/11150146/7109067/340db5c8-e164-11e4-9f59-d744d0d5ade3.png)

**Comment by yutarochan** [comment]
Patched: Appended availability charts to both the User Profile Page and Dashboard User Cards.
