### ISSUE TITLE
IE11 for Win7 - receiving a notification - I am notified via a popup that there is a notification, but I cannot open it

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#68]
![image](https://cloud.githubusercontent.com/assets/11150146/7109025/9ab01196-e163-11e4-89c3-f62a15729b26.png)

I am notified of a notification. I have to refresh my screen to go up and see it. When I open the notifications window, nothing appears in the dropdown.

**Comment by yutarochan** [comment]
Patched: All in-app notification issues have been fixed and should work for both IE and Chrome.
