### ISSUE TITLE
IE11 for Win7 - profile setup process - database ID is displayed

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#71]
Instead of the course name, the database ID of the course is displayed as I add them to my profile.

![image](https://cloud.githubusercontent.com/assets/11150146/7109090/e2a3a390-e164-11e4-8543-88a167b7f283.png)

![image](https://cloud.githubusercontent.com/assets/11150146/7109094/02104756-e165-11e4-8385-26305e2533d9.png)

**Comment by yutarochan** [comment]
Patched: Courses should now show up as actual course name.
