### ISSUE TITLE
Name got switched

### ISSUE THREAD

**Issue by pi-paticha** [WeStudee/WeStudee#76]
I think the name somehow got switched...Yuya, did you send me a testing request earlier? 
![screen shot 2015-04-15 at 7 58 23 pm](https://cloud.githubusercontent.com/assets/11206258/7171714/e7b9415e-e3a9-11e4-8817-525119314a7b.png)

**Comment by yutarochan** [comment]
Yeah, I realized this just about a couple of hours ago. Going to patch this up tonight after the testing is completely finished (to avoid the risk of breaking something.)

Problem with coding at 4 AM in the morning haha
