### ISSUE TITLE
Navigation from "Profile", back to "My Courses" page is not present

### ISSUE THREAD

**Issue by derrick773** [WeStudee/WeStudee#8]
I cannot navigate to the "My Courses" page. There is no button or dropdown that provides that functionality.

**Comment by derrick773** [comment]
Using Google Chrome v40.0.2214.115 m on Windows 7 on my laptop

**Comment by derrick773** [comment]
![image](https://cloud.githubusercontent.com/assets/11150146/6320331/0fffe81e-baa8-11e4-9206-294ee30e20de.png)

**Comment by yutarochan** [comment]
Closed - Added Dashboard link, which is the equivalent of the "My Courses" page.
